name: datamining
dependencies:
  - jupyter
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - statsmodels
  - gensim
  - matplotlib
  - seaborn
  - nltk
  - cython
  - pip:
    - git+https://github.com/napsternxg/pyLDAvis.git
    - wordcloud
    - tweepy
