name: datamining
dependencies:
  - python=2
  - jupyter
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - statsmodels
  - gensim
  - matplotlib
  - seaborn
  - nltk
  - cython
  - pip:
    - https://github.com/napsternxg/pyLDAvis/zipball/master
    - wordcloud
    - tweepy
    - pydotplus
